### ISSUE TITLE
Reduce the number of branches

### ISSUE THREAD

**Issue by mb010865** [gematik/api-ti-messenger#143]
It might be good, if the number of branches are reduced so that we can follow up easier. The suggestion would be to have a main and a develop branch only so that we can follow up either the already confirmed content on a main branch or the newest specification work on develop. And old branches might also be deleted.

**Comment by gem-lat** [comment]
Hallo, werden wir nach dem Service-Patch von TIM 1.1.1 berücksichtigen. Aktuelle Themen zum Service-Patch werden im feature/ C_11306-Branch bearbeitet. Nach der Veröffentlichung vom Service-Patch werden wir dies in den main-Branch mergen.
