### ISSUE TITLE
Dokumentation vom Search API ist verschwunden

### ISSUE THREAD

**Issue by christian-frei** [gematik/api-ti-messenger#151]
https://github.com/gematik/api-ti-messenger/blob/main/docs/

Das Dokument FHIR-Directory-search-api.adoc ist mitsamt dem Branch "search-api" verschwunden und anscheinend weder in den develop noch den main branch gemergt worden.

Koennen Sie das bitte wiederherstellen?

**Comment by gem-lat** [comment]
Hallo,

das ist korrekt. Die Aufrufe der VZD-FHIR-Directory Endpoints wird ab jetzt hier beschrieben: https://github.com/gematik/api-ti-messenger/blob/develop/docs/FHIR-Directory.adoc
