### ISSUE TITLE
Endpoint für die Federationlist und Format

### ISSUE THREAD

**Issue by mb010865** [gematik/api-ti-messenger#154]
In der Openapi Beschreibung wird als Endpunkt zum Abruf der Federationlist /FederationList/federationList.jws angegeben, in der Spezifikation ist dagegen /FederationList/federationList.json als Endpunkt angegeben. 
Welche URL ist die richtige?
Ferner wird in der Spezifikation angegeben, dass das Format gemäß RFC7515 JWS ist, das Beispiel ist jedoch nicht in einem validen JWS Format. 
Sollen wir das angegebene Format aus dem Beispiel voraussetzen oder ein korrektes JWS Format?

**Comment by spilikin** [comment]
Moin,
richtige URL ist: `/tim-provider-services/FederationList/federation.jws`, z.B. https://fhir-directory-test.vzd.ti-dienste.de/tim-provider-services/FederationList/federation.jws


JSON wurde durch signierten JWS ersetzt nach der Sicherheitsanalyse. Prefix `/tim-provider-services` ist in der Spezifikation uneindeutig, habe einen Korrektur-Ticker erstellt. Danke!

**Comment by spilikin** [comment]
Richtige URL ist:

`/tim-provider-services/FederationList/federationList.jws` 

Die Spezifikation wird korrgiert bzw. beim Prefix `/tim-provider-services` klarer formuliert. Danke!
