### ISSUE TITLE
Einladungsprüfung im TIM client

### ISSUE THREAD

**Issue by benkuly** [gematik/api-ti-messenger#155]
_Dies ist abgeleitet aus ANFTIM-147 und ANFTIM-198. Dieses Ticket soll eine öffentliche Diskussion anregen._

### Die Einladungsprüfung findet aktuell spezifiziert auf dem Fachdienst statt:
![image](https://user-images.githubusercontent.com/12199167/213997894-8d2d426a-09bd-4adf-a9a6-5343a56c8423.png)

### Daraus ergeben sich verschiedene Probleme:
1. ❌ Speicherung von Kontakt-Daten auf Servern – Erstellung sozialer Graphen
2. ❌ Vertrauen des Servers notwendig - Zero-Trust Ansatz wird verletzt
3. ❌ Nutzer muss vorher einer Einladung zustimmen – schlechte UX
4. ❌ Neue Endpunkte notwendig - Kompatibilität mit Matrix Spec nicht gegeben
5. ❌ Viele Nutzer bei erfolgreichem Angriffen auf Fachdienst betroffene.

Aus Nutzersicht ist es sinnvoll, wenn auch Einladungen angesehen werden können, die ohne Freigabe reingekommen sind. Dies sollte vom Nutzer z. B. als Filter explizit aktiviert werden oder in einer separaten Liste angezeigt werden, damit der Nutzer nicht von Spam belastet wird. Der Nutzer sollte auch die Möglichkeit haben einzustellen, dass alle unbekannten Einladungen automatisch abgelehnt werden. Dies entspricht dann dem aktuell spezifiziertem Verhalten - nur client seitig.

Technisch ist dies lösbar, in dem man die Liste der freigegebenen Nutzer mittels Matrix account data (bestenfalls verschlüsselt) speichert. Dadurch ist diese Liste client-übergreifend nutzbar und wird auf dem Server nicht mehr benötigt. Die Prüfung findet dann dementsprechend im Gegensatz zur aktuellen Spec lokal beim Client statt. Der Client kann außerdem im VZD überprüfen, ob Einladungen von einer berechtigten Person stammen, wenn diese nicht in der lokalen Freigabeliste existiert.

![image](https://user-images.githubusercontent.com/12199167/213998047-98c73720-1001-4763-830d-cdc01840467e.png)

### Vorteile dieser Lösung:
1. ✅ Keine lesbare Speicherung von Kontakt-Daten auf Servern (verschlüsselt)
2. ✅ Kein Vertrauen des Servers notwendig
3. ✅ Nutzer kann bei Bedarf auch „unangeforderte“ Einladungen einsehen
4. ✅ Keine neue Endpunkte notwendig
5. ✅ Sehr kleiner Angriffsvektor: Nutzer selbst muss komprommitiert werden.

Um den Zeitplan nicht zu gefährden, könnte die Freigabeliste zunächst unverschlüsselt gespeichert und in einer späteren Ausbaustufe verschlüsselt werden.

**Comment by benkuly** [comment]
Ich möchte an dieser Stelle nochmals betonen, dass es sich hier um einen signifikanten Unterschied in Entwicklungs- und Betriebsaufwand handelt. Während die hier vorgestellte Alternative mit Standard-SDKs umgesetzt werden kann, indem einfach ein neuer Event-Typ hinzugefügt wird, muss bei der bisherigen Lösung der Proxy deutlich mehr Aufgaben übernehmen und benötigt zudem eine Datenbank, die vorher ggf. gar nicht notwendig war.

**Comment by mlangguth** [comment]
Ich unterstütze diesen Punkt und möchte aus Perspektive der Flexibilität für die Nutzer ergänzen, dass mit diesem Ansatz die Kontrolle darüber, wer mich erreichen darf, wieder beim einzelnen Nutzer liegen kann - und nicht über harte Server-VZD-Strukturen vorgegeben wird.
Dies ist insbesondere dann wichtig, wenn die Versicherten dazu kommen, da es Leistungserbringer gibt, die durch Versicherte angesprochen werden können WOLLEN (die meisten nicht, einige aber schon).
Und diese Entscheidung, wer mich erreichen können soll, sollten Ärzte individuell steuern können - auch in Hinblick auf ihre Kollegen (auf Ebene einzelner Accounts, Rollenkennungen der anderen Teilnehmer sowie Domänenzuordnungen).
Die Verwendung von account_data und dem bereits vorhandenen Mechanismus m.ignored_user_list bietet sich an. Dieser könnte für unseren Branchen-Messenger erweitert auf m.ignored_role_list, m.ignored_domaine_list etc.

**Comment by mkk-sbl** [comment]
Die vorgebrachten Punkte von @benkuly sind nachvollziehbar und die dargestellte Lösung erscheint sinnvoll, vor allem sofern die Umsetzung wie dargestellt gemäß der Matrix Spezifikation erfolgt.

**Comment by mlangguth** [comment]
Die Nutzererwartung, (in einem Vollausbau, der natürlich nicht in Stufe 1 gänzlich umgesetzt werden muss) sehe ich aus meinen Gesprächen und Erfahrungen im ärztlichen Bereich:


_Als Nutzer möchte ich steuern können, wer mich zum Chat in neuen Räumen einladen darf, damit ich u.a. die Kontrolle über mein chatbezogenes Arbeitsaufkommen habe._

Akzeptanzkriterien (stichpunktartig). "Nutzer muss einstellen können, ..."

- dass jeder andere TIM-Nutzer ihn einladen darf
- dass nur interne TIM-Nutzer (gleiche Organisation) ihn einladen dürfen
- dass nur Nutzer im eigenen Adressbuch ihn einladen dürfen
- dass nur TIM-Nutzer auf der von ihm gepflegten Whitelist ihn einladen dürfen
- dass TIM-Nutzer auf der von ihm gepflegten Blacklist ihn nicht einladen dürfen
- dass alle TIM-Nutzer von ihm festgelegter Organisationen ihn einladen / nicht einladen dürfen
- dass alle TIM-Nutzer von ihm festgelegter Rollen (Ärzte, Apotheker, Pflegende - später Versicherte) ihn einladen / nicht einladen dürfen
- Administrator muss auf User-Ebene einstellen können, ob die Kommunikation mit externen TIM-Nutzern unterbunden wird

**Comment by mkk-sbl** [comment]
Sehr gut. So wird das Ganze doch schon deutlich anschaulicher :-) 

Als Nutzer möchte ich nachvollziehen können, wer mir eine Einladung zum Chat sendet, damit ich weiß wer meine Daten einsehen kann.

Akzeptanzkriterien (stichpunktartig). "Nutzer muss ..."

- leicht erkennen können wenn eine Einladung akzeptiert wurde
- nachvollziehen können wenn und warum eine Einladung abgelehnt wurde

**Comment by mlangguth** [comment]
Auch diesen Punkt möchte ich dringlich noch einmal zur Diskussion "hochbringen"...

**Comment by benkuly** [comment]
**Ich würde mir von der gematik mehr Transparenz wünschen. Woran scheitert denn das Einbringen dieser von allen Seiten (auch der gematik!) gewünschten Änderung? Der Vorschlag liegt nun schon seit über einem halben Jahr bei der gematik und ist seit einem halben Jahr hier öffentlich.**

**Comment by mlangguth** [comment]
In der TIM-Sprechstunde letzten Freitag machte die gematik deutlich, dass sie KEINE Änderungen an der TIM 1.1 Spezifikation mehr vornehmen werde, die nicht zwingend als Fehlerbeseitigung notwendig sei, um den Starttermin im Herbst nicht zu gefährden.
Dass die dann kommenden Produkte aufgrund nicht gelöster Punkte wie dieser mit deutlichen Akzeptanzproblemen rechnen müssen, spielt dabei keine Rolle. Der Termin geht (erneut) vor.

**Comment by benkuly** [comment]
Kleines Update: Das beschriebene Konzept ist nun in der Vorabveröffentlichung für TI-M 2.x verwendet worden :tada: 

Es heißt außerdem:
> Das bedeutet jedoch, dass das neue Berechtigungsmodell auch für TIM 1.x Implementierungen eingeführt werden muss.

**Comment by mlangguth** [comment]
Ja, hat mich auch sehr gefreut. Allerdings ist die vorliegende Spec noch nicht ganz da, wo sie hin müsste. Aber es ist ja auch erst einmal ein "Grobentwurf". Also Ärmel hoch gekrempelt... 😃

**Comment by benkuly** [comment]
Ich würde dieses Ticket mal schließen, da es nun auch in der Vorabversion gelandet ist.

**Comment by mlangguth** [comment]
Naja, als geschlossen würde ich es noch nicht betrachten, da wesentliche Anteile bislang in der Spec fehlen.
Was man sich als Nutzer - und als Verantwortlicher eine Einrichtung! - wünschen würde, wären wie im letzten Jahr aufgezählt noch:
- dass nur interne TIM-Nutzer (gleiche Organisation) ihn einladen dürfen
- dass nur Nutzer im eigenen Adressbuch ihn einladen dürfen (ohne diese einzeln angeben zu müssen)
- dass alle TIM-Nutzer von ihm festgelegter Organisationen ihn einladen / nicht einladen dürfen
- dass alle TIM-Nutzer von ihm festgelegter Rollen (Ärzte, Apotheker, Pflegende - später Versicherte) ihn einladen / nicht einladen dürfen
- Administrator muss auf User-Ebene einstellen können, ob die Kommunikation mit externen TIM-Nutzern unterbunden wird

Ich würde mich freuen, wenn wir das Ticket verwenden könnten, um gemeinschaftlich zu diskutieren, welche der Punkte für TIM 2.0 benötigt werden und welche bis wann folgen sollten.
Gerade die Einschränkung der Kommunikation auf "nur intern" halte ich für wichtig. Insbesondere auch, dass ein OrgAdmin das für die eigenen Nutzer einstellen können muss, ohne dass diese es überschreiben können.

**Comment by Johennes** [comment]
Das in Account Data persistierte Berechtigungskonzept mit Block- und Allow-Listen für Nutzer und Domains ist im Juni mit TI-M Basis und TI-M ePA veröffentlicht worden. Im anstehenden TI-M Pro Release wird es zusätzlich die [Möglichkeit](https://github.com/gematik/api-ti-messenger/blob/develop/src/schema/TI-M_Pro/permissionConfig_V1.json#L36) geben auch Ausnahmen für Versicherte als Gruppe zu definieren.

Aus der Aufzählung im letzten Post bleiben daher nur noch folgende Punkte:

> * dass nur Nutzer im eigenen Adressbuch ihn einladen dürfen (ohne diese einzeln angeben zu müssen)
> * dass alle TIM-Nutzer von ihm festgelegter Rollen (Ärzte, Apotheker, Pflegende [...]) ihn einladen / nicht einladen dürfen
> * Administrator muss auf User-Ebene einstellen können, ob die Kommunikation mit externen TIM-Nutzern unterbunden wird

Sofern Interesse besteht die technische Lösung dieser konkreten Probleme weiter zu diskutieren, würde ich darum bitten separate Issues dazu zu öffnen da es hier sonst wahrscheinlich nur geringe Überschneidungen gibt.
