### ISSUE TITLE
Event replacement

### ISSUE THREAD

**Issue by mlangguth** [gematik/api-ti-messenger#164]
ein fachliches Thema, was wir vermutlich noch ausarbeiten müssen:

Ab v1.4 definiert Matrix ein (optionales) Modul, zum Editieren (Ersetzen) vorheriger Nachrichten:

https://spec.matrix.org/v1.5/client-server-api/#event-replacements

Wir sind zwar noch auf v1.3, werden aber sicher in absehbarer Zeit auf eine neuer Matrix-Version wechseln - und dann brauchen wir eine Klärung zu diesem Thema:

Im TIM-Kontext ist das nachträgliche Editieren aus Gründen der Revisionssicherheit (vermutlich) unerwünscht. Daher sollte die Umsetzung / Bereitstellung dieses Moduls durch die gematik für TIM untersagt werden.

Alternativ bräuchte es eine intensivere Beschäftigung, in welchen Fällen ein Bearbeitung sinnvoll und zulässig wäre und wie auf die alten Werte zugegriffen werden könnte…

Aus Gründen der Interoperabilität und um einrichtungsübergreifende Prozesse auf Basis abgestimmter Funktionsumfänge aller unterschiedlichen Anbieter erstellen zu können, sollte dieses Thema in den gematik-Vorgaben geregelt werden. Das sollte fachlich in der Runde besprochen werden.

**Comment by benkuly** [comment]
Das Bearbeiten von Nachrichten halte ich schon nicht für falsch. Dennoch könnte man den angesprochenen Sorgen begebnen, indem man erzwingt (MUSS), dass man sich die Historie bearbeiteter Nachrichten auf Klick sehen können muss.

**Comment by mb010865** [comment]
Ich halte dieses Feature für gefährlich. Nicht umsonst haben die grossen Messenger es nicht umgesetzt und werden es auf absehbare Zeit nicht umsetzen.
Ich antworte auf Messages, die sich nachträglich verändern? Schon die Funktion "Für alle löschen" in WA ist teilweise verwirrend.
Da hilft auch eine Historiendarstellung wenig in der UX.
Noch schlimmer wäre das Feature, wenn man an M2M Kommunikation denkt oder Attachments. 
Und in der Tat ist es für die Implementierung eine erhebliche Erhöhung der Komplexität.

**Comment by mlangguth** [comment]
Volle Zustimmung. Daher sollte aus meiner Sicht die Verwendung der Funktion "event replacement" in TIM durch die gematik normativ untersagt werden. Zumindest solange, bis in einem Folgerelease vielleicht ein tragfähiges Konzept gefunden (und der Endnutzerbedarf für eine solche Funktion in einem med-Messenger bestätigt wird).

**Comment by AlexB030** [comment]
Das ist ein interessanter Punkt. Aus eigener Erfahrung kann ich sagen, das ich die Editieren-Funktion in Messengern, die das anbieten, viel nutze... vor allem im mobilen Kontext, wo übereifrige Autokorrektur oftmals ganze Wörter ersetzt und der Sinn mglw. abhanden kommt.
Wenn es aber erlaubt werden sollte und wir einmal annehmen, dass das Versionieren technisch keinen Mehraufwand bedeuten würde, halte ich das trotzdem für eine Große Herausforderung hinsichtlich Usability. Mir ist bisher kein System untergekommen, welches versionieren kann und dies gleichzeitig noch übersichtlich darstellt, wenn es zu mehr als einer Änderung kam.
Zusätzlich müsste das auch ordentlich von Bots abgebildet werden, die auf Basis von Nachrichten im Chat bestimmte Aktionen triggern, und wenn es nur die Archivierung ist.
Ich werde den Punkt mal intern mit unseren Architekten besprechen, da kommen wir um Zuge eines Upgrades von 1.3 nach 1.x sowieso nicht herum.

**Comment by ofegem** [comment]
Momentan gibt es keine TI-M Spezifikation, die die Protokollversion 1.4 oder 1.5 vorsieht. Wie Du @mlangguth aber schon richtig vermutest, ist das Feature "Event Replacement" ebenfalls nicht vorgesehen, vor allem aus Gründen der Prozesssicherheit, des Informationserhalts und einer angenehmen UX.

Sollte die Protokollversion spezifikatorisch auf >= v1.4 festgelegt werden, so würden wir Deinem Vorschlag nachkommen und die Nutzung dieses Features explizit regeln im Sinne von Untersagen der Nutzung, sofern nicht bis dahin auftauchende zwingende fachliche oder technische Gründe dagegen sprechen.

**Comment by mlangguth** [comment]
Prima, danke. Das schafft Klarheit.
