### ISSUE TITLE
Inhalt der QR-Codes zum Austausch der MXIDs

### ISSUE THREAD

**Issue by mlangguth** [gematik/api-ti-messenger#166]
Für die Kontaktaufnahme zwischen zwei Nutzer wird in den Specs ein Prozess beschrieben, bei dem ein QR-Code zum Einsatz kommt. Ein Client (oder etwas anderes) zeigt diesen QR-Code an, der andere Client scannt diesen ein - der Kontakt wird etabliert.

Allerdings habe ich keine näheren Informationen dazu gefunden, welche Daten in welchen Form in welchem Typ eines QR-Codes enthalten sein sollen. Das wäre für eine interoperable Nutzung zwischen unterschiedlichen, zugelassenen TIM-Clients aber notwendig.

Im Rahmen der Ticketkommunikation wurde verwiesen auf :
    https://spec.matrix.org/v1.5/client-server-api/#qr-codes
was allerdings nicht hilft, da es dort nur um eine Validierungsfunktion geht und in den dort definierten Inhalten des QR-Codes die MXID (soweit ich sehen konnte) nicht enthalten ist - wohl aber Schlüsselmaterial, welche für die reine Übermittlung der MXID nicht enthalten sein sollte.

**Comment by AlexB030** [comment]
Wir haben intern schon über diese Problematik gesprochen. Anlass war tatsächlich auch das von Ihnen eingestellte Ticket. 

Wir sind uns in dem Zusammenhang nicht ganz sicher, woher die Annahme kam, dass über den QR-Code auch die MXID ausgetauscht werden könne aber das müssen wir korrigieren. Einen konkreten Plan haben wir dafür aber noch nicht.

**Meine persönliche Meinung** ist, dass ich den QR-Code als Austauschformat charmant finde, besonders dann, wenn sich einzelne Nutzer dafür entscheiden nicht-sprechende MXIDs zu verwenden, obwohl dies mit dem nächsten Release der Spec erlaubt sein soll.

**Comment by mlangguth** [comment]
OK.
Wenn wir nicht-sprechende MXIDs weiterhin ermöglichen wollen (womöglich auch noch sehr lange Bezeichner), dann müssen wir meiner Ansicht nach auch einen Mechanismus zum gezielten Austausch der MXIDs anbieten. Da mir der VZD-FHIR in der aktuell spezifizierten Form wenig praxistauglich erscheint, sollte man dafür nicht ausschließlich auf den VZD setzen - da die Eintragung der MXID in den VZD ohnehin nur optional ist.
Vor dem Hintergrund wäre (mindestens) ein QR-Code schon sinnvoll (auch wenn er am PC nicht wirklich weiterhilft).

Als Lösung kann man einfach auf vCard 4.0 aufsetzen und die MXID in die IMPP-Section schreiben:
[https://www.rfc-editor.org/rfc/rfc6350#section-6.4.3]

Da das ganze einfach ein Text ist, lässt sich dann auch als normalen QR-Code darstellen.

**Comment by benkuly** [comment]
> Als Lösung kann man einfach auf vCard 4.0 aufsetzen und die MXID in die IMPP-Section schreiben

Oder noch besser QR code gleich als [Matrix URI](https://spec.matrix.org/v1.5/appendices/#uris) `matrix://`, dann öffnet sich nach dem scan gleich der client.

**Comment by mlangguth** [comment]
Entspricht zwar nicht dem vCard-Strukturgedanken (unter IMPP sollten alle Messenger rein), kann man aber natürlich trotzdem machen. 
Wobei ich dann eher für `tim://` wäre, damit gleich der richtige Messenger-Typ gewählt wird 😉

**Comment by gem-lat** [comment]
Hallo @benkuly und @mlangguth,

hier ein Vorschlag der in die Client-Spezifikation einfließen soll:

**2D-Barcode erstellen und anzeigen**
Der TI-Messenger-Client MUSS eine Funktion bereitstellen, 2D-Barcodes zu erstellen und diese auf dem Display des Endgerätes anzuzeigen. Hierbei MUSS der 2D-Code in eine QR-Code-Darstellung gemäß ISO/IEC 18004:2006 kodiert werden. Als Inhalt für die Generierung des 2D-Codes MUSS das folgende JSON-Array verwendet werden:

`{    
 “Displayname“ : “<Displayname>“,     
 “MXID“ : “matrix://<MXID>“
 }`
 

**2D-Barcode scannen und weiterverarbeiten**
Der TI-Messenger-Client MUSS eine Funktion bereitstellen, die es dem Akteur erlaubt über die Kamera des Endgerätes einen 2D-Barcode in eine QR-Code-Darstellung einzuscannen. Der TI-Messenger MUSS den eingescannten 2D-Code gemäß ISO/IEC 18004:2006 decodieren und den Displaynamen und die Matrix-User-ID aus dem Attribut Displayname und MXID dem Akteur anzuzeigen, damit dieser die Aufnahme in die Freigabeliste bestätigen oder ablehnen kann. Zusätzlich MUSS der TI-Messenger-Client die MXID in seine lokale Kontaktliste übernehmen.


Dabei ist zu beachten, das der Anwendungsfall gemäß Kapitel "Directnachrichten" in der Client-Spezifikation erfüllbar ist. Da es sich hierbei eher um ein logisches Problem handelte (Kontaktaustausch / gleich einen Raum erstellen) wurden die beiden RFC-Texte als Vorschlag erstellt.

**Comment by mlangguth** [comment]
Danke für den Vorschlag. Ich würde folgende Veränderungen vornehmen bzw. vorschlagen:

- Verpflichtung zur Ansteuerung einer Kamera nur für Smartphones und Tablets. Am PC / Notebook ist das eher kein Use Case und verkompliziert die Implementierung nur unnötig (als Pflichtfunktion)
- Statt "matrix://" bitte "tim://" verwenden, wir wollen ja keinen Matrix-Client triggern, sondern nur unsere TIM-Clients. Dazu sollte die gematik auch prüfen / einleiten, dass TIM als Endpunkt registriert / gesichert wird. (nicht, dass wir hier Kollisionen mit anderen Produkten haben werden)
- Eventuell sollte dann auch von "MXID" auf "TIMID" gewechselt werden?
- Insgesamt hielte ich eine vCard 4.0 für sinnvoller (siehe oben), dann werden die Nutzungsmöglichkeiten umfangreichen. (Dies auch vor dem Hintergrund, dass nur "Displayname" für eine Identifikation einer Person wirklich nicht ausreicht...)
- Eine Verpflichtung zur Anzeige und Übernahme in die lokale Kontaktliste halte ich für nicht sinnvoll, da sich ein Nutzer ja nach dem Scannen z.B. auch dagegen entscheiden können muss. Es sollte reichen, dass der TIM-Client das Scannen und Verarbeiten dieser QR-Codes unterstützen können muss (sofern Kamera vorhanden). Wie und was er damit genau macht, sollte herstellerspezifisch bleiben (mindestens solang wir die lokale Kontaktliste nicht genormt haben).

**Comment by benkuly** [comment]
Eine synchronisierung mit der lokalen Kontaktliste sollte meiner Meinung nach verhindert werden. Viele Mobil-Betriebssystem synchronisieren die lokale Kontaktliste. Spätestens bei Patienten ist das ein großes Problem.

Ich tendiere auch zum standardisiertem Format vCard und dort das Feld IMPP, welches für instant messaging entwickelt wurde und dem Überfliegen nach auch eine `matrix://` bzw. `tim://` URI akzeptiert.

Sollte sich dennoch für ein JSON entschieden werden, so sollte dies eher so aussehen:
```json
{
    "name": "Dr. Müller",
    "uri": "matrix:u/mueller:beispiel.de"
}
```
Denn dies würde es auch erlauben beliebige Matrix-Ressourcen als QR-Code zu teilen:
```json
{
    "name": "öffentliche Verbandsnews",
    "uri": "matrix:r/verbandsnews:beispiel.de"
}
```

Ich würde im Falle von JSON dafür plädieren, dass man bei `matrix://` und `MXID` bleibt. Da der QR-Code mit solch einem selbstdefiniertem Json-Schema nur aus dem TI-Messenger heraus gelesen werden kann, besteht dafür kein Bedarf.

Außerdem: Gemäß Matrix-Spezifikation muss eine matrix-uri mit mxid folendermaßen aussehen: `matrix:u/alice:example.org`

**Comment by mlangguth** [comment]
Gute Punkte. Vielleicht sollten wir noch mal klären, was wir unter "lokaler Kontaktliste" verstehen? Ist damit die im TIM-Client integrierte TIM-eigene Kontaktliste gemeint oder die Kontaktliste des Smartphone (basierend auf dem jeweiligen OS)?

Bei Matrix vs. TIM bleibe ich skeptisch, da die QR-Codes ja von jeder Kamera gelesen werden können. Das kann dann in normalen Matrix-Clients durchaus zu Problemen führen (die dann wieder bei unseren Nutzern aufschlagen und Supportaufwand verursachen).

**Comment by gem-lat** [comment]
@mlangguth, vielen Dank für dein Feedback. 

Dein Punkt zur Verwendung von Kameras auf Desktop-Anwendungen kann ich nachvollziehen. Würde ich anpassen zu „_Der TI-Messenger-Client für mobile Szenarien MUSS eine Funktion…_“. 

Wie @benkuly schon vorgeschlagen hat, würden wir auch als Schema `matrix://` (das wäre auch Spec-konform: https://spec.matrix.org/v1.5/appendices/#uris) bevorzugen.

Wir können uns auch gerne auf eine vCard-Lösung einigen. Hier mal ein Vorschlag:
```
BEGIN:VCARD
VERSION:4.0
N:<Name>;<Vorname>
IMPP:matrix://<MXID>
END:VCARD
```

Ggf. Kann dies vom jeweiligen Hersteller optional um weitere Parameter ergänzt werden? Was meint ihr dazu?

Meine Annahme war eigentlich, dass es im TI-Messenger-Client eine eigene lokale Kontaktliste gibt. Diese muss natürlich vom Betriebssystem getrennt sein, da es sich um die Speicherung Person bezogener Daten handelt. 

Wenn sich 2 Personen treffen, dann wollen Sie ihre Kontaktdaten austauschen (QR-Code-Scan). Wenn es jetzt keine lokale TI-Messenger Kontaktliste gäbe, dann müsste ein Raum mit den jeweiligen Kontaktpersonen erstellt werden (was passiert sonst mit der MXID, die ich jetzt erhalten und auf die jeweilige Freigabeliste gesetzt habe). In der Praxis wird es doch eher so sein, dass sich die Personen bei Bedarf kontaktieren wollen und hierfür in ihre lokale Kontaktliste die andere Person suchen werden. Das meinte ich übrigens mit einem „logischen Problem“.

**Comment by benkuly** [comment]
Ein Gedanke zum Thema vCards ist mir noch gekommen: An sich sind vCards sehr gut geeignet, dennoch sehe ich das Problem, dass nicht nur ein TI-Messenger vCards lesen kann, sondern auch die Kamera-App des Telefons. Hier wird also jederzeit die "Gefahr" bestehen, dass dienstliche Kontakte auf privaten Geräten mit der Google oder Apple Cloud synchronisiert werden.

Ob ein QR-Code-Scan in der Praxis überhaupt oft vorkommt bezweifle ich persönlich. Dennoch wäre es ja logisch, wenn der Kontakt auf der Freigabeliste landet, die damit quasi einer TIM-interne Kontaktliste entspricht.

**Comment by jkoops27** [comment]
@gem-lat Moin, die Formulierung "mobile" Szenarien („Der TI-Messenger-Client für mobile Szenarien MUSS eine Funktion…“) finde ich in Zeiten von iOS-Apps auf MacOS & Android auf Windows 11 ebenfalls uneindeutig. Außerdem gibt ja auch einige Geräte, die keine Kamera haben oder deren Verwendung nicht erlaubt wurde. Dafür muss es einen alternative Methode geben, z.B. Übernahme aus der Galerie

**Comment by Johennes** [comment]
Die vCard-Variante ist mittlerweile in [TI-M Basis](https://gemspec.gematik.de/docs/gemSpec/gemSpec_TI-M_Basis/latest/#A_25398) veröffentlich worden, so dass ich diesen Issue als erledigt ansehen würde.
