### ISSUE TITLE
Fragen zu /search Dokumentation

### ISSUE THREAD

**Issue by christian-frei** [gematik/api-ti-messenger#169]
Ich habe ein paar Fragen zu der Search Dokumenation:
https://github.com/gematik/api-ti-messenger/blob/develop/docs/FHIR-Directory.adoc#312-search-request

### Organization vs. Healthcare Service
unter 3.1.2 steht
>To search for an organization entrie use:
/search/HealthcareService
>
>To search for a practitioner entrie use:
/search/PractitionerRole

Das ist etwas verwirred, da ich dann eigentlich einen endpoint `/search/Organization` erwarten würde.

### Im Bezug auf einen org-admin client:
Die Beziehung Organization-HealthcareService ist 1-n. 

Wäre es demnach nicht eher sinnvoll, wenn man nach der Organization sucht (telematik id) und anschliessend alle HealthcareServices (inkl. Locations und Endpoints) erhält? 
Schliesslich möchte ein Org-Admin Benutzer die ganze Organization (basierend auf der eindeutigen telematik id) verwalten können. Das FHIR Bundle bietet sich ja bestens dafür an.

### Request Beispiele
Momentan gibt es nur dieses Beispiel
`GET https://fhir-directory.vzd.ti-dienste.de/search/HealthcareService?organization.active=true&endpoint.status=active&_include=*&_count=2&_pretty=true`
ich sehe nur meta-parameter; mir fehlen da die eigentlich Search-Parameter (name, id, providedBy etc).
Gelten die Parameter, wie sie im Testtreiber beschrieben sind? wenn ja, bitte ich um Abgleich der Dokumentation mit dem Testtreiber.

die HL7 spec (https://www.hl7.org/fhir/healthcareservice.html#search) passt demnach nicht mit den im Testtreiber beschriebenen Parametern zusammen.

**Comment by gem-cp** [comment]
Der HealthcareService enthält die Referenzen zu den Ressourcen Organization, Location und Endpoint. Das FHIR-Directory unterstützt die verkettete Suche. D. h., wenn man nach dem Namen der Organization sucht, wäre der Suchparameter providedBy.name. Daher ist HealthcareService (oder für die Personensuche PractitionerRole) der Einstiegspunkt für die Suche.
Zusätzlich: die Angabe organization.active=true müsste meiner Meinung nach heißen: providedBy.active=true

**Comment by gem-cp** [comment]
Der HealthcareService enthält die Referenzen zu den Ressourcen Organization, Location und Endpoint. Das FHIR-Directory unterstützt die verkettete Suche. D. h., wenn man nach dem Namen der Organization sucht, wäre der Suchparameter organization.name. Daher ist HealthcareService (oder für die Personensuche PractitionerRole) der Einstiegspunkt für die Suche.

**Comment by christian-frei** [comment]
Damit wird es allerdings schwierig für einen org-admin der z.B. in einem grossen Spital arbeitet:
Das Spital (Organization) hat eventuell ein Dutzend Abteilungen (HealthcareServices), die möchte er ja nicht alle einzeln abfragen, sondern den Einstiegspunkt auf der obersten Ebene haben. Er könnte sich wie einem Directory durch die Abteilungen zu den Locations und Endpunkten runterhangeln.
Mit Hilfe des _revinclude und der _include parameter ist dies durchaus möglich, z.B. so in der Art:
`.../search/Organization?organization.name=foo&_revinclude=HealthcareService&_include=Location,Endpoint`

**Comment by gem-cp** [comment]
Mit .../search/HealthcareService?organization.name=foo&_include=* werden **alle** HealthcareService Ressourcen gefunden, die mit der Organisation oder den Organisationen mit name= foo per Referenz verkettet sind. Ein zusätzliches _revinclude wird so vermieden.

**Comment by christian-frei** [comment]
Ach so, ja dann ist ja alles gut :-)

Jetzt nur noch zwei Fragen zum Testtreiber: 
- Mapping der Testtreiber queryParameter zum HL7 search api:
   da hat es z.B. einen queryParam `The telematikId of the TIOrganization.`
Wie wird das im Search Request abgebildet: `organization.telematikId`? 
   Die Organization Struktur hat die TelematikID tief verpackt:

```json
{
                  "resourceType": "Organization",
                  "id": "OrganizationExample001",
                  "meta": {
                    "profile": [
                      "https://gematik.de/fhir/directory/StructureDefinition/OrganizationDirectory"
                    ]
                  },
                  "identifier": [
                    {
                      "system": "https://gematik.de/fhir/sid/telematik-id",
                      "value": "9-2.58.00000040"
                    }
                  ]
}
```

Wird der VZD da "Convenience-parameter" anbieten? 
   Wenn ja, gelten diejenigen die im Testtreiber ersichtlich sind oder kriegen wir da noch eine Liste in der VZD Spec, damit wir unseren org-admin client bauen können.

- wollt ihr die Namensgebung der Testtreiber Endpunkte noch anpassen? TIOrganization ist ja nicht mehr im Simplifier als FHIR Objekt aufgeführt, heisst ja nur noch Organization (auch TIPractitioner).
