### ISSUE TITLE
Testtreiber Endpunkte anpassen

### ISSUE THREAD

**Issue by christian-frei** [gematik/api-ti-messenger#171]
* Mir ist im Testtreiber yaml aufgefallen, dass dort noch von TIOrganization und TIPractitioner die Rede ist. Die sind jedoch im Simplifier als Organization und Practitioner aufgeführt.
Koennt ihr das bitte anpassen.

* Ausserdem hat es noch einen Typo "searchHealthcareService**Endpont**InFhirDirectory"

**Comment by TVRiddle** [comment]
Hallo, 

vielen Dank. Die Anpassungen wurden übernommen.

**Comment by christian-frei** [comment]
Besten Dank Herr Voldemort.
