### ISSUE TITLE
Vulnerability in search-token flow

### ISSUE THREAD

**Issue by christian-frei** [gematik/api-ti-messenger#177]
Ich beziehe mich auf den Flow beschrieben in: https://github.com/gematik/api-ti-messenger/blob/develop/docs/use-cases/VZD-search.adoc

Im speziellen auf den Teil, in dem VZD den Matrix Homeserver aufruft:
![Screenshot 2023-03-02 at 11 07 55](https://user-images.githubusercontent.com/27783410/222398033-658d0464-4b33-42d8-8912-86a14b113abb.png)

#### Wir sehen eine Vulnerability: 
Mit dem Matrix Token kann jede erdenkliche Matrix REST Ressource aufgerufen werden (getMessages, sync, register users.. ).

#### Unser Vorschlag:
- VZD verwaltet den Matrix Public Key im DomainManagement zusammen mit dem SHA256 gehashten Domainnamen, in einem zusätzlichen Feld.
- Anstelle von `GET /tim-authenticate... (Auth Header mit Matrix-OpenID-Token)` ruft der client VZD mit einem signierten JWT auf, der als QueryParam mitgeben wird. 
  Die gehashte Domain wird ebenfalls als QueryParam mitgegeben.
- VZD holt mit der gehashten Domain den Public Key aus dem Domain-Mgmt und prüft das signierte JWT Token damit.
- der Rückruf auf den Matrix server entfällt

#### Vorteile:
- weniger HTTP Traffic
- keine Vulnerability mehr

**Comment by jweko** [comment]
zu "_Mit dem Matrix Token kann jede erdenkliche Matrix REST Ressource aufgerufen werden (getMessages, sync, register users.. )._"
Ich hatte es so verstanden, dass das Matrix OpenID Token verwendet wird, das man vorher über https://spec.matrix.org/v1.3/client-server-api/#post_matrixclientv3useruseridopenidrequest_token erhalten hat. Mit diesem Token kann doch nur die UserInfo Schnittstelle aufrufen sonst keine anderen Matrix Rest Ressourcen?

**Comment by ichderjens** [comment]
Hallo, 

genau so ist es gedacht. Der OpenID-Token ist der Token, den Sie sich über die Schnittstelle https://matrix.org/docs/api/#post-/_matrix/client/v3/user/-userId-/openid/request_token von einem Homeserver ausstellen können. (Wenn Sie bereits eingeloggt sind und einen Access_Token besitzen) 
"Gets an OpenID token object that the requester may supply to another service to verify their identity in Matrix. The generated token is only valid for exchanging for user information from the federation API for OpenID.

The access token generated is only valid for the OpenID API. It cannot be used to request another OpenID access token or call /sync, for example." 
Ist es Ihnen gelungen mit diesem Token Zugriff auf andere Teile der API zu erhalten?

**Comment by christian-frei** [comment]
Ich hatte es missverstanden: ich dachte, das openId token sei ein JWT. 
Wenn das openId Token ein random String ist, der auf Matrix zwischengespeichert wird, ganz ähnlich wie die session_id beim /register workflow, ist alles in Ordnung. Danke für die Klarstellung.
