### ISSUE TITLE
2FA sollte aus Akzeptanzgründen konfigurierbar sein (A_22936)

### ISSUE THREAD

**Issue by mlangguth** [gematik/api-ti-messenger#180]
Link zur Diskussion auf gemmunity
https://www.gemmunity.de/community?id=community_question&sys_id=761470691bb5e510b5e531dc8b4bcbf6

**Comment by AlexB030** [comment]
Hallo @mlangguth, ich habe dazu in der gemmunity geantwortet, damit andere Kommentierende zu Ihrem Post das auch sehen können.

Viele Grüße

**Comment by Johennes** [comment]
Ich schließe diesen Issue damit wir das Thema nicht mehrfach tracken.
