### ISSUE TITLE
Matrix Proxy: Define error message when server is not in federation list

### ISSUE THREAD

**Issue by christian-frei** [gematik/api-ti-messenger#183]
Damit die Matrix Clients alle gleich damit umgehen können, wenn der MatrixHost nicht in der Federationlist ist, brauchen wir eine Erweiterung der Matrix Spec.

Ich schlage vor dass wir eine JSON Struktur gemeinsam mit einem 403 FORBIDDEN zurückgeben. (analog zu den Matrix Fehlermeldungen).
z.B.
```json
{
  "errcode": "M_HOST_FORBIDDEN",
  "error": "Server not in federation list"
}

**Comment by gem-lat** [comment]
Hallo @christian-frei,

das Thema betrifft den CR_006 der auch in das kommende TIM Service Patch mit einfließt. 

Aktueller Vorschlag:

_Responsecode 403 
{ 
   "errcode": " M_FORBIDDEN ",  
   "error": "Die Gegenpartei konnte nicht kontaktiert werden"  
}_ 

Wir würden auch gerne die Standard Error Codes verwenden:
https://spec.matrix.org/v1.6/client-server-api/#standard-error-response

**Comment by mb010865** [comment]
Hallo @gem-lat 

generell ist es gut, die Standard-Responses zu verwenden. Für das Debugging im Client wäre es jedoch sinnvoll zu wissen, dass der Zugriff wegen der Federation List verboten ist.

**Comment by jweko** [comment]
Hi zusammen,
in den Sequenzdiagrammen zu dem Use Case ist in der aktuellen Spec sowie hier https://github.com/gematik/api-ti-messenger/blob/feature/C_11306/images/diagrams/TI-Messenger-Dienst/Ressourcen/UC_Approvel_List_Seq.svg allerdings aktuell **401** statt 403 angegeben. Ist dies dann nur als Empfehlung zu verstehen? Ansonsten wäre es gut die Sequenzdiagramme auch anzupassen, wenn das geändert werden soll auf 403. 

Ich überlege grade, ob man überhaupt eine Vereinheitlichung der Error Codes im Body zwingend benötigt an dieser Stelle? Man bekommt ja zumindest diese Fehlermeldung normal vom Messenger Proxy, der zum Client "gehört"?

**Comment by Johennes** [comment]
HTTP Status Code sowie Error Code und Message sind mittlerweile in https://gemspec.gematik.de/docs/gemSpec/gemSpec_TI-M_Basis/latest/#A_25534 festgelegt worden.
