### ISSUE TITLE
TIM muss mehr werden, als nur ein "normaler" Messenger mit Fallbezug

### ISSUE THREAD

**Issue by mlangguth** [gematik/api-ti-messenger#184]
Hallo zusammen,

wir hatten das Thema ja schon auf dem Konnektathon und in der letzten Sprechstunde:
Reicht es, dass TIM ein Messenger ist - oder muss er doch mehr liefern, damit Kliniken ihre bestehenden Messenger-Lösungen gegen TIM tauschen und niedergelassene Praxen darauf anspringen?

Ich habe mal eine kleine Umfrage auf Twitter und LinkedIn durchgeführt, natürlich nicht repräsentativ. Aber es zeigt schon ein gewisses Stimmungsbild auf:

**Twitter:**
https://twitter.com/MLangguth/status/1645804012460187658?s=20
![image](https://user-images.githubusercontent.com/16609810/232841661-14f42136-368a-429c-8888-741dfa7b2073.png)

:

**LinkedIn:**
https://www.linkedin.com/feed/update/urn:li:activity:7051566315471269889/
![image](https://user-images.githubusercontent.com/16609810/232841895-32b575d1-cd97-41ff-b5a9-20149efb99d0.png)

Auf LinkedIn kann ich sehen wer abgestimmt hat. Bei dieser Umfrage leider nicht so viele Ärzte dabei. Insgesamt waren es nur 5. Davon reicht es aber nur einem, chatten zu können. 2 brauchen mindestens Entlastung für die MFAs, der Rest noch mehr.

::

Ich denke es zeigt - auch wenn es nur kleine Umfragegrößen sind - dass wir mit TIM mehr liefern müssen, als lediglich eine Option auf Messages, die mit einem Fallbezug versehen werden können.

Ich möchte daher anregen, dass wir uns gemeinsam zeitnah (nächsten 4 Wochen) um den Start der Erarbeitung fachlicher Szenarien kümmern, die mit wenig technischem Aufwand über TIM abbildbar wären. Dies idealerweise als Co-Creation unter Einbeziehung von Ärzten, MFAs, Pflege und PraxisOrga-Experten.

Eure Meinung dazu?

**Comment by Johennes** [comment]
Ich glaube dieses Thema wird aktiv durch unsere Produktmanager vorangetrieben und es gab auf diesem Issue hier seit über einem Jahr keine Aktivät mehr. Darüber, dass TIM mehr können muss als Chatten sind wir uns denke ich auch einig und arbeiten mit dem Thema Bots bereits in diese Richtung. Daher schließe ich diesen Issue.
