### ISSUE TITLE
ContactMgmt HTTP Authorization Header

### ISSUE THREAD

**Issue by christian-frei** [gematik/api-ti-messenger#185]
In der [OpenApi Spec zum Contact Management](https://github.com/gematik/api-ti-messenger/blob/develop/src/openapi/TiMessengerContactManagement.yaml) steht:
> The TI-Messenger-Client uses a Matrix-OpenID-Token from his Messenger-Service for
    authentication on all REST operations. The bearer token can be obtained from the
    homeserver. (POST /_matrix/client/r0/user/{userId}/openid/request_token).

Wie sieht der HTTP Header genau aus? 

Können Sie das bitte in der open-api spec ergänzen? (und hier schon mal vorgängig angeben, damit ich die Implementierung abschliessen kann)

Besten Dank

**Comment by gem-lat** [comment]
Hallo @christian-frei ,

hier ein Beispiel für die userID: @alice:example.com:
```
POST /_matrix/client/r0/user/%40alice%3Aexample.com/openid/request_token HTTP/1.1
Content-Type: application/json

{}
```

Quellen:
https://matrix.org/docs/spec/client_server/r0.6.0.html#post-matrix-client-r0-user-userid-openid-request-token
https://matrix.org/docs/api/#post-/_matrix/client/v3/user/-userId-/openid/request_token

**Comment by christian-frei** [comment]
Danke fuer die Antwort, aber ich glaube, Sie haben meine Frage missverstanden.

Eigentlich war die Frage, wie der HTTP Header aussehen soll, der bei der Kommunikation mit allen `/tim-contact-mgmt/v1.0/` REST Ressourcen verlangt wird:
>The TI-Messenger-Client uses a Matrix-OpenID-Token from his Messenger-Service for authentication on all REST operations. 

Koennen Sie bitte einen Beispiel Header zeigen (und auch in der OpenAPI Spezifikation nachtragen)?

**Comment by Johennes** [comment]
Es handelt sich um ein Bearer Token, dass wie [hier](https://swagger.io/docs/specification/authentication/bearer-authentication/) beschrieben im `Authorization`-Header gesetzt wird.

**Comment by christian-frei** [comment]
danke für die schnelle Antwort :-)

**Comment by Johennes** [comment]
"Nur" 15 Monate zu spät, ich weiß. 😅🙈

Wir versuchen hier besser zu werden in Zukunft.
