### ISSUE TITLE
C_11306, AF_10061-01 - Einladung von Akteuren außerhalb einer Organisation

### ISSUE THREAD

**Issue by mlangguth** [gematik/api-ti-messenger#188]
Hallo zusammen,

bei der Prüfung der Vorabveröffentlichung fällt auf, dass der Vorgang der Einladung von Teilnehmern aus Fremd-Domänen noch nicht angepasst wurde. Der aktuelle Mechanismus der "Freigabeliste" wird im Feld nicht funktionieren und die Akzeptanz völlig zerstören!
Es ist widersinnig einem TIM-Nutzer zu sagen, dass er Einladungen von anderen Teilnehmern erst sehen kann, wenn er die Absender selbst auf eine Whitelist eingetragen hat. Abbildung 6 spiegelt eben gerade nicht den Ablauf wieder, den die Nutzer erwarten, da sich die Nutzer eben NICHT zuerst live treffen, um sich gegenseitig QR-Codes zu zeigen.

Wir haben das Thema schon vor langem adressiert:
#155 

Ich möchte erneut dringlich anregen, dass dieser Punkt in einer Form gelöst wird, der der Nutzererwartung entspricht. Lösungsvorschläge haben wir in 155 besprochen. In dieser Form, das wiederhole ich gerne, wird TIM im ambulanten Bereich für Ärzte, Apotheken und die Pflege scheitern!

**Comment by Johennes** [comment]
Wie in https://github.com/gematik/api-ti-messenger/issues/155#issuecomment-2275842041 erklärt sollte sich dieses Problem mit den kürzlich erfolgten Releases von TI-M Basis und TI-M ePA erledigt haben.
