### ISSUE TITLE
C_11306, A_22797-01 - Automatische Löschfunktion 

### ISSUE THREAD

**Issue by mlangguth** [gematik/api-ti-messenger#189]
Hallo zusammen,

nicht als Ticket, sondern als Frage in die Runde (vielleicht habe ich das Matrix-Protokoll falsch verstanden):

**A_22797-01 - Automatische Löschfunktion** des TIM-Clients soll über C_11306 wie folgt definiert werden:
_TI-Messenger-Clients MÜSSEN über eine automatische Löschfunktion verfügen. 
Von dieser automatischen Löschfunktion sind alle lokal vorgehaltenen Räume und Rauminhalte betroffen, wenn (1) der Nutzer nicht mehr Mitglied des Raumes ist, oder (2) der Raum server-seitig gelöscht wurde.[<=]_ 

Ich lese die AFO bzgl. (1) so, dass in dem Moment (bzw. ausgesprochen zeitnah), wo ein Nutzer nicht mehr Member eines Raums ist (weil er den Raum selbst verlassen hat oder herausgeworfen wurde), die lokalen Nachrichten und Anhänge gelöscht werden - obwohl der Nutzer soweit ich das Matrixprotokoll verstehe, auf alle Einträge zugreifen darf, die in die Dauer seiner Mitgliedschaft fallen. Oder?

Fachlich gesprochen:
Ein Arzt wird für eine Zweitmeinung in einen bestehenden Raum mit bestehender Kommunikation gebeten. Dort diskutiert er für eine Weile mit und nachdem er durch ist, verlässt er den Raum (oder wird mit Verabschiedung daraus ausgeschlossen). Direkt ab diesem Zeitpunkt sind alle Nachrichten, an denen der Zweitmeinungsarzt beteiligt war, für ihn selbst nicht mehr erreichbar.
Das kann fachlich nicht gewollt sein. Er müsste mindestens die Möglichkeit haben, seinen anteiligen Chatverlauf exportieren zu können. Das ist bei "Rauswurf" aber schwierig zu timen (wie lange soll es möglich sein?).

1. Ist meine Annahme zum Matrixprotokoll korrekt oder verliert er doch direkt die Lesemöglichkeiten der alten Nachrichten?
2. Wie ist die Meinung der Gruppe und der gematik zur fachlichen Sicht / dem fachlichen Bedarf?

Beste Grüße
Mark Langguth

**Comment by Johennes** [comment]
> 1. Ist meine Annahme zum Matrixprotokoll korrekt oder verliert er doch direkt die Lesemöglichkeiten der alten Nachrichten?

Das ist meiner Ansicht nach korrekt. Technisch gesehen wird für die Sichtbarkeit von Events der Room State _zum Zeitpunkt der Events_ ausgewertet: https://spec.matrix.org/v1.11/client-server-api/#server-behaviour-5

> 2. Wie ist die Meinung der Gruppe und der gematik zur fachlichen Sicht / dem fachlichen Bedarf?

Wie in den Kommentierungsworkshops im Mai besprochen wird das Löschkonzept als ganzes in Zukunft noch weiter ausgearbeitet. Beim Thema Exportieren von Chats könnten auch Bots, die wir als Anwendungsszenario demnächst ausarbeiten, hilfreich sein.

Da es hier seit letztem Mai kein weiteres Feedback gegeben hat, schließe ich diesen Issue.
