### ISSUE TITLE
Vereinfachung Testtreiber SearchOrganizationResponse 

### ISSUE THREAD

**Issue by christian-frei** [gematik/api-ti-messenger#193]
Die im Testtreiber definierte Response für `/devices/{deviceId}/fhir/searchOrganizationInFhirDirectory` sieht momentan so aus:
```json
{
  "totalSearchResults": 42,
  "searchResults": [
    {
      "Organization": {
        "organizationId": "fa2b79c8-ed57-11ec-8ea0-0242ac120002",
        ...
      },
      "HealthcareService": {
        "healthcareServiceId": "1a62648f-55a7-42d5-ab7f-841e78be390e",
        ...
      },
      "Endpoint": {
        "endpointId": "7dee886f-ce5e-4879-9c36-3407825ad374",
        ...
      }
    }
  ]
}
```
Das funktioniert aber nur, wenn genau nur eine Organization gefunden wird, welche auch nur genau einen HealthcareService und genau einen Endpoint hat.

Das FHIR SearchBundle ist da wesentlich flexibler.

Können wir nicht einfach das FHIR SearchBundle, welches von VZD kommt, als Response weitergeben?
Das ist einerseits einfacher zu implementieren und andererseits können  die Testtreiber Spezifikateure lediglich auf die FHIR Spec verweisen.

**Comment by TVRiddle** [comment]
Wird in #146 weiter besprochen
