### ISSUE TITLE
Testtreiber: GetHealthcareServices - Parameter fehlt

### ISSUE THREAD

**Issue by christian-frei** [gematik/api-ti-messenger#198]
In der OpenApi Spec steht:
>Get healthcareServices regarding the named organizationId

Leider fehlt aber der Parameter `organizationId`

Vorschlag:
`GET
/devices/{deviceId}/fhir/org/healthcareService/{organizationId}`

**Comment by awesome-manuel** [comment]
Eine `deviceId` ist eindeutig einer Organization zugeordnet. Daher gehen wir davon aus, dass hier nur die "eigenen" HealthcareServices geliefert werden müssen.

**Comment by christian-frei** [comment]
Einverstanden.

Um die OpenApi Spec zu verbesssern und zukünftige Fragen auszuschliessen:
1. erwähnen, dass eine DeviceId einer TelematikId (und schliesslich einer Organisation) zugeordnet ist
2. den Satz entfernen:
> Get healthcareServices regarding the named organizationId

**Comment by TVRiddle** [comment]
Die Testtreiberschnittstelle wurde dahingehend angepasst:
1. Bitte beachtet, dass das Schema DeviceInfo bereits das Feld "TelematikId" beinhaltet
2. Satz wurde verändert und Unklarheiten zu vermeiden.
