### ISSUE TITLE
Test-treiber device_id sollte ein String sein

### ISSUE THREAD

**Issue by christian-frei** [gematik/api-ti-messenger#199]
im Test-treiber ist die device_id ein `int`.
Das widerspricht aber der Matrix spec: 
https://spec.matrix.org/v1.5/client-server-api/#post_matrixclientv3login
>device_id	
string	
ID of the client device. If this does not correspond to a known client device...

Oder ist hier die Annahme, dass der Test-treiber nicht die gleichen Devices verwendet wie der matrix server?

**Comment by TVRiddle** [comment]
2tes ist der Fall. Eine Testtreiberschnittstelle stellt mehrere Devices zur Verfügung die mit dem gleichen Homeserver verbunden sind und sich auch in der Art (OrgAdmin, OrgUser oder HbaUser) gleichen. An jeder Schnittstelle müssen mindestens 3 Devices liegen (an der OrgAdmin Schnittstelle reicht 1, siehe https://github.com/gematik/TI-Messenger-Testsuite/blob/main/doc/userguide/Testsuite.adoc#3-akteure-in-der-ti-messenger-testsuite)

Die DeviceId dient der Testsuite nur zur Identifikation eines Geräts, das durch den Testtreiber zur Verfügung steht und hat nichts mit Matrix zu tun.

**Comment by christian-frei** [comment]
Alles klar, danke für die Erklärung.
