### ISSUE TITLE
Test-treiber claim device request

### ISSUE THREAD

**Issue by christian-frei** [gematik/api-ti-messenger#200]
Der device claim request sieht so aus:
```json
{
  "claimerName": "some name",
  "claimFor": 180
}
```

die response:
```json
{
  "deviceId": 4711,
  "deviceName": "awesome_device_01",
  "deviceStatus": "claimed",
  "claimer": "some name",
  "claimerCn": "gematik GmbH",
  "cn": "Dr Renate Grunner",
  "telematikId": "Grunner-test-only",
  "claimedUntil": "2022-04-01T08:30:00Z"
}
```

1. fehlt im request nicht `claimerCn`? wie soll der Adapter das bestimmen?
2.  `"claimFor": 180`: sind das Sekunden oder Minuten?
3. zur Vereinfachung kann der request param `claimerName` in `claimer` umbenannt werden, damit er synchron mit der Response ist.

**Comment by MidNight88** [comment]
Hi, 
1. claimerCn soll nicht im Request sein, die claimerCn kann aus dem gelieferten clientCert bestimmt werden, da wir mTLS zur Kommunikation verwenden
2.  es handelt sich hier um Sekunden
3. werden wir angleichen
