### ISSUE TITLE
Test-treiber unclaim device response

### ISSUE THREAD

**Issue by christian-frei** [gematik/api-ti-messenger#201]
die unclaim response ist folgendermassen definiert:
```json
{
  "deviceId": 4711,
  "deviceName": "awesome_device_01",
  "deviceStatus": "claimed",
  "claimer": "some name",
  "claimerCn": "gematik GmbH",
  "cn": "Dr Renate Grunner",
  "telematikId": "Grunner-test-only",
  "claimedUntil": "2022-04-01T08:30:00Z"
}
```
1. `deviceStatus` sollte neu `unclaimed` sein
2. `claimer`, `claimedUntil` und `claimerCn` sollten nicht länger in der response sein

**Comment by TVRiddle** [comment]
Hi Christian,

hier wird das gleiche Schema wie in claim device verwednet. Leider kann man nicht schnittstellenspezifisch Beispiel Angaben in den Schematas angeben. Natürlich ist die Aussage richtig. Es sollte `unclaimed` als Status und `claimer`, `claimUntil` und `claimerCn` sollte auf `null`gesetzt werden. 

Wenn wir dies ändern kann müsste nur um die Beispiele zu ändern eine weitere Ressource und ein anderer Datentyp hinzugefügt werden.

Hoffe das klärt die Verwirrung.

Besten Gruß
