### ISSUE TITLE
AF_10103 - Reihenfolge der Requests

### ISSUE THREAD

**Issue by awesome-manuel** [gematik/api-ti-messenger#202]
1. In https://github.com/gematik/api-ti-messenger/blob/main/images/diagrams/TI-Messenger-Dienst/Ressourcen/UC_10103_Seq.png sieht es so aus (zumindest kann man es so interpretieren), dass der erste Request "GET /authorize" vom Registrierungsdienst Frontend an den Authenticator geht und dieser den Request an den IDP weiterleitet.
2. In https://github.com/gematik/api-ti-messenger/blob/feature/C_11306/images/diagrams/TI-Messenger-Dienst/Ressourcen/UC_10103_Seq.png ist es jedoch eindeutig so, dass der IDP vom Registrierungsdienst Frontend direkt kontaktiert wird und mit einem Redirect auf den Authenticator antwortet.

Wir haben das akutell nach 1. implementiert und das scheint zu funktionieren. Für 2. ist nicht klar, welcher Endpoint am IDP das sein soll (ein `auth_endpoint` ist in der IDP Spezifikation nicht zu finden) und wie dieser genau angesprochen wird.

**Comment by ichderjens** [comment]
Hallo, 

vielen Dank für den Hinweis. Wir haben das angesprochene Sequenzdiagram aktualisiert. https://github.com/gematik/api-ti-messenger/blob/feature/C_11306/docs/use-cases/MS-AF10103-authenticate-organization.adoc

Viele Grüße
Jens Neubert
