### ISSUE TITLE
Fallunterscheidung für /owner-authenticate fehlt

### ISSUE THREAD

**Issue by awesome-manuel** [gematik/api-ti-messenger#203]
In https://github.com/gematik/api-ti-messenger/blob/feature/C_11306/docs/TI-Messenger-Client.adoc#112-owner-authenticate wird beschrieben, wie ein `owner-accesstoken` ausgestellt werden kann. Dies ist in zwei Fällen nötig:

1. HBA-User will seinen Endpoint in der PractitionerRole ändern (Authentifizierung über HBA am zentralen IDP)
2. OrgAdmin will HealthcareServices bearbeiten (Authentifizierung über Registrierungsdienst)

Diese beiden Anwendungsfälle sind, was die Authentifizierung angeht grundverschieden. Das sollte in der Beschreibung besser herausgearbeitet werden.

**Comment by Johennes** [comment]
Der Link scheint leider tot zu sein. Falls sich dieses Problem in der aktuellen Spec-Version noch wieder findet, bitte ich um Rückmeldung.

**Comment by awesome-manuel** [comment]
> Der Link scheint leider tot zu sein. Falls sich dieses Problem in der aktuellen Spec-Version noch wieder findet, bitte ich um Rückmeldung.

Ist nach wie vor noch etwas einseitig für den Messenger-Client geschrieben: https://github.com/gematik/api-ti-messenger/blob/main/docs/Client/Client.adoc#owner-authenticate

**Comment by Johennes** [comment]
Danke. Ich habe den Text mit https://github.com/gematik/api-ti-messenger/commit/aa26ba486309b467539d58e6540e865d545b78ea verbessert.
