### ISSUE TITLE
Einsatz von integrationsmanagern erlaubt?

### ISSUE THREAD

**Issue by mlangguth** [gematik/api-ti-messenger#210]
Hallo zusammen,

ich bin gerade darüber gestolpert, dass die Spec keine Aussage zum Einsatz von Integrationsmanagern (zB scalar.vector.im) trifft. Nur das serverseitige (!) Bridging ist verboten.

Wie verhält es sich mit Integrationsmagern, um z.B. Jitsi für Gruppen-Calls einzubinden?
Erlaubt?
Verboten?
Und würde das für den Einsatz von Bots nicht zwingend benötigt werden!?

**Comment by benkuly** [comment]
Solange Integrationsmanager nicht Teil der Matrix Spec sind würde ich davon abraten, dass es in irgendeiner Weise verwendet wird.

**Comment by Johennes** [comment]
Der Einsatz von Integration Managern ist aktuell weder normativ vorgegeben noch verboten. Integration Manager sind, wie bereits erwähnt, aktuell nicht Teil der Matrix Spezifikation. Scalar ist der [proprietäre](https://github.com/element-hq/element-integration-manager/issues/86#issuecomment-2051364194) Integration Manager von Element. Ein Integration Manager _kann_ die Konfiguration von Bots und anderen App Services zwar vereinfachen, ist dazu aber nicht zwingend erforderlich.
