### ISSUE TITLE
Einsatz von Matrix 2.0 bei TI-M ?

### ISSUE THREAD

**Issue by AlinaLuft** [gematik/api-ti-messenger#222]
Die Matrix Foundation hat die Version 2.0 ihres Kommunikationsprotokolls veröffentlicht. 

Wird der TI-Messenger in der zweiten Ausbaustufe auf Matrix 2.0 aufsetzen?

Falls nicht, um welche Version wird es sich handeln?
```[tasklist]
### Tasks
```

**Comment by benkuly** [comment]
Matrix 2.0 wurde lediglich angekündigt. Es gibt noch viele offene Baustellen. Eine Veröffentlichung ist meines Wissens erst in mehreren Monaten geplant.

**Comment by AlinaLuft** [comment]
Eine Information über die Einbeziehung von Matrix 2.0 ist für die Entwicklung des Messengers unerlässlich, da die Matrix-Version 2.0 wesentliche Änderungen/Features mitbringen wird.
Für eine gesicherte Planung ist es wichtig zu wissen, welche Matrix-Version TI-M 2.0 nutzen wird.

**Comment by Johennes** [comment]
Wir planen für dieses Jahr ein Update von aktuell 1.3 auf eine höhere Version. Matrix 2.0 ist zum jetzigen Zeitpunkt aber eine _Vision_, keine Version. Die aktuelleste Version der Matrix Spezifikation ist 1.10. Die nächste Ausbaustufe von TI-M kann daher nicht auf Matrix 2.0 basieren.
