### ISSUE TITLE
ContactMgmt metadata endpoint

### ISSUE THREAD

**Issue by awesome-michael** [gematik/api-ti-messenger#223]
Die OpenAPI Spezifikation des [ContactMgmt](https://github.com/gematik/api-ti-messenger/blob/main/src/openapi/TiMessengerContactManagement.yaml)  sieht vor dass der Basispfad, auf dem die Metadaten abgefragt werden können z.B.  `/tim-contact-mgmt/v1.0.2/ ` lautet. Die Versionsnummer ist also immer fester Bestandteil des Pfades. Ein Client kann doch aber nicht im Voraus wissen welche Version der API die aktuell gültige ist, also wie der Pfad auszusehen hat. Aus diesem Grund ist die Versionsnummer vermutlich auch Bestandteil der Metadaten.
Wäre es nicht viel sinnvoller die Metadaten auf `/tim-contact-mgmt/` auszuliefern, so dass ein Client auch ohne das Wissen über die aktuelle Version diese abfragen kann? Aus der Antwort kann der Client dann die aktuelle Versionsnummer extrahieren und den korrekten Pfad für alle anderen Endpunkte ableiten.

**Comment by Johennes** [comment]
> Wäre es nicht viel sinnvoller die Metadaten auf /tim-contact-mgmt/ auszuliefern, so dass ein Client auch ohne das Wissen über die aktuelle Version diese abfragen kann?

Ja, das macht Sinn. Für die Contact-Management-API werden wir das nicht mehr anpassen weil diese API mit dem TI-M Basis Release vom Juni entfallen ist. Wir werden das aber für neue APIs (z.B. https://github.com/gematik/api-ti-messenger/blob/develop/src/openapi/TiMessengerInformation.yaml) aufgreifen.

CC @ichderjens
