### ISSUE TITLE
Broken links in FHIR-Directory.adoc

### ISSUE THREAD

**Issue by HarHarLinks** [gematik/api-ti-messenger#244]
https://github.com/gematik/api-ti-messenger/blob/eb1d6b0045a7b3a51541fe62750477912333eca5/docs/FHIR-Directory/FHIR-Directory.adoc?plain=1#L88-L90

these lead to 404

**Comment by Johennes** [comment]
Looks like `gemILF_VZD_FHIR_Directory` is missing between the two slashes in the middle for some reason. These work:

 * https://github.com/gematik/api-vzd/blob/gemILF_VZD_FHIR_Directory/1.0.1/docs/FHIR_VZD_HOWTO_Search.adoc#21-fhirdirectorysearchapi-search-for-practitioners-and-organizations
 * https://github.com/gematik/api-vzd/blob/gemILF_VZD_FHIR_Directory/1.0.1/docs/FHIR_VZD_HOWTO_Owner.adoc#2-fhirdirectoryownerapi

**Comment by Johennes** [comment]
Fixed in https://github.com/gematik/api-ti-messenger/pull/251.
